/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CiteRouteImport } from './routes/cite'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as ResultsLayoutRouteImport } from './routes/results/_layout'
import { Route as ResultsLayoutRawRouteImport } from './routes/results/_layout/raw'
import { Route as ResultsLayoutUniprotAccessionRouteImport } from './routes/results/_layout/uniprot/$accession'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CiteRoute = CiteRouteImport.update({
  id: '/cite',
  path: '/cite',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsLayoutRoute = ResultsLayoutRouteImport.update({
  id: '/results/_layout',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsLayoutRawRoute = ResultsLayoutRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ResultsLayoutRoute,
} as any)
const ResultsLayoutUniprotAccessionRoute =
  ResultsLayoutUniprotAccessionRouteImport.update({
    id: '/uniprot/$accession',
    path: '/uniprot/$accession',
    getParentRoute: () => ResultsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cite': typeof CiteRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/imprint': typeof ImprintRoute
  '/legal': typeof LegalRoute
  '/methods': typeof MethodsRoute
  '/terms': typeof TermsRoute
  '/results': typeof ResultsLayoutRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/results/raw': typeof ResultsLayoutRawRoute
  '/results/uniprot/$accession': typeof ResultsLayoutUniprotAccessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cite': typeof CiteRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/imprint': typeof ImprintRoute
  '/legal': typeof LegalRoute
  '/methods': typeof MethodsRoute
  '/terms': typeof TermsRoute
  '/results': typeof ResultsLayoutRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/results/raw': typeof ResultsLayoutRawRoute
  '/results/uniprot/$accession': typeof ResultsLayoutUniprotAccessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cite': typeof CiteRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/imprint': typeof ImprintRoute
  '/legal': typeof LegalRoute
  '/methods': typeof MethodsRoute
  '/terms': typeof TermsRoute
  '/results/_layout': typeof ResultsLayoutRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/results/_layout/raw': typeof ResultsLayoutRawRoute
  '/results/_layout/uniprot/$accession': typeof ResultsLayoutUniprotAccessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cite'
    | '/faq'
    | '/glossary'
    | '/imprint'
    | '/legal'
    | '/methods'
    | '/terms'
    | '/results'
    | '/settings/api-keys'
    | '/results/raw'
    | '/results/uniprot/$accession'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cite'
    | '/faq'
    | '/glossary'
    | '/imprint'
    | '/legal'
    | '/methods'
    | '/terms'
    | '/results'
    | '/settings/api-keys'
    | '/results/raw'
    | '/results/uniprot/$accession'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cite'
    | '/faq'
    | '/glossary'
    | '/imprint'
    | '/legal'
    | '/methods'
    | '/terms'
    | '/results/_layout'
    | '/settings/api-keys'
    | '/results/_layout/raw'
    | '/results/_layout/uniprot/$accession'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CiteRoute: typeof CiteRoute
  FaqRoute: typeof FaqRoute
  GlossaryRoute: typeof GlossaryRoute
  ImprintRoute: typeof ImprintRoute
  LegalRoute: typeof LegalRoute
  MethodsRoute: typeof MethodsRoute
  TermsRoute: typeof TermsRoute
  ResultsLayoutRoute: typeof ResultsLayoutRouteWithChildren
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cite': {
      id: '/cite'
      path: '/cite'
      fullPath: '/cite'
      preLoaderRoute: typeof CiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/_layout': {
      id: '/results/_layout'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/_layout/raw': {
      id: '/results/_layout/raw'
      path: '/raw'
      fullPath: '/results/raw'
      preLoaderRoute: typeof ResultsLayoutRawRouteImport
      parentRoute: typeof ResultsLayoutRoute
    }
    '/results/_layout/uniprot/$accession': {
      id: '/results/_layout/uniprot/$accession'
      path: '/uniprot/$accession'
      fullPath: '/results/uniprot/$accession'
      preLoaderRoute: typeof ResultsLayoutUniprotAccessionRouteImport
      parentRoute: typeof ResultsLayoutRoute
    }
  }
}

interface ResultsLayoutRouteChildren {
  ResultsLayoutRawRoute: typeof ResultsLayoutRawRoute
  ResultsLayoutUniprotAccessionRoute: typeof ResultsLayoutUniprotAccessionRoute
}

const ResultsLayoutRouteChildren: ResultsLayoutRouteChildren = {
  ResultsLayoutRawRoute: ResultsLayoutRawRoute,
  ResultsLayoutUniprotAccessionRoute: ResultsLayoutUniprotAccessionRoute,
}

const ResultsLayoutRouteWithChildren = ResultsLayoutRoute._addFileChildren(
  ResultsLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CiteRoute: CiteRoute,
  FaqRoute: FaqRoute,
  GlossaryRoute: GlossaryRoute,
  ImprintRoute: ImprintRoute,
  LegalRoute: LegalRoute,
  MethodsRoute: MethodsRoute,
  TermsRoute: TermsRoute,
  ResultsLayoutRoute: ResultsLayoutRouteWithChildren,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
